### ISSUE TITLE
CNE02 - Exposition d'une URL vers un bucket

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#258]

**Comment by thomashbrnrd** [comment]
Le bucket qui était exposé était celui ci : https://storage.gra.cloud.ovh.net/v1/AUTH_df731a99a3264215b973b3dee70a57af/basegun-public.
Je l'ai passé en privé. Cependant il héberge la dernière version du modèle. Je vais trouver une autre solution pour héberger le modèle.
