### ISSUE TITLE
Intégration du parcours d'identification des armes à blanc

### ISSUE THREAD

**Issue by nutfdt** [datalab-mi/Basegun#276]

**Comment by ClemGerard** [comment]
je vous propose de clôturer ce ticket puisque je vais détailler le contenu fonctionnel

**Comment by nutfdt** [comment]
Afficher 13 photos, si tu en sélectionne une -> Catégorie C (arme d'alarme)
Si tu cliques sur "Pas de correspondance" on te donne la catégorie de la typologie trouvé.
