### ISSUE TITLE
Explorer la possibilité de refondre les typologies de l'algo de classification

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#311]
Fusionner les typologies semi auto ne semble pas apporter de gain significatif des performances

Discuter avec les experts de la possibilité de diviser la typologie autre pistolet

**Comment by AurelienmartW** [comment]
##Test de fusion des semi auto effectué
Résultats non concluants

##Découpage de la typologie autre pistolets
-Discussion avec les experts
-Exploration de clustering en cours pour trouver de nouvelles typologies

**Comment by AurelienmartW** [comment]
-Le clustering fais ressortir 2 sous typologies que nous appellerons autre pistrolet court et autre pistolets long

-Un premier entrainement avec ces 2 sous typologies n'a pas été concluant, cela semble venir d'erreur dans le dataset

-Un tri manuel des sous-typologies a été effectué et un nouvel entrainement est en cours

**Comment by AurelienmartW** [comment]
-Après un tri manuel du dataset, les resultats ne présentent toujours pas d'amélioration

-Une piste était un déséquilibrage des classes, cependant la loss est adaptée selon ces dernières pour rééquilibrer la répartition

-Cela peut venir d'un manque global de photo

-Récupération d'images depuis Naturabuy en cours pour augmenter la volumétrie de la typologie autre pistolet en cours
