### ISSUE TITLE
Comportement attendu de la page d identification d'une arme d alarme

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#362]
On précise ici le comportement de la page d'identification d'une arme d'alarme en fonction des actions de l'utilisateur.

##Task

- [x] En cochant une des 13 cases correspondant à une arme d'alarme présentes sur la page la catégorie légale retournée est **D.**
- [x] En cochant "aucune correspondance", on retourne la catégorie légale de la typologie de l'arme.

**Comment by ClemGerard** [comment]
@nutfdt attention modification de la catégorie légale à afficher : D au lieu de C.

Cf COPROJ du 20 : D'après Antoine P on est en attente de la signature par le conseil d'état du passage en catégorie C

**Comment by nutfdt** [comment]
> @nutfdt attention modification de la catégorie légale à afficher : D au lieu de C.
> 
> Cf COPROJ du 20 : D'après Antoine P on est en attente de la signature par le conseil d'état du passage en catégorie C

<img width="185" alt="catd" src="https://github.com/datalab-mi/Basegun/assets/49862152/e244dfc8-73d7-47f2-83cf-c142ce0c7e54">
