### ISSUE TITLE
Corriger / vérifier la redirection des users vers la PROD

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#365]
Les utilisateurs ont remonté des problèmes de redirection à l'ouverture de l'app.
Cette erreur de redirection semble "inconsistante" au bout d'un moment les utilisateurs sont bien redirigés.

- [x]  vérifier que la TWA pointe bien vers la PROD
- [x] vérifier qu'il n'y a pas d'autre URL (de tests par ex) qui restent dans la TWA
- [ ] forcer / sécuriser la redirection vers basegun.interieur.gouv.fr

**Comment by thomashbrnrd** [comment]
Je ne pense pas qu'on puisse "forcer la redirection". Si c'est une config DNS c'est pas vraiment de notre ressort et il faudrait peut-être plutôt voir avec ceux qui gère la configuration des NEOs.

**Comment by ClemGerard** [comment]
> Je ne pense pas qu'on puisse "forcer la redirection". Si c'est une config DNS c'est pas vraiment de notre ressort et il faudrait peut-être plutôt voir avec ceux qui gère la configuration des NEOs.

Je suis d'accord avec toi, il s'agit d'une tâche qui ne semble pas à priori de notre ressort.
J'ajoute en commentaire dans ce ticket, que j'ai relancé le CNE Antunes sur le sujet pour qu'ils prenne le relais côté Equipe NEO

**Comment by ClemGerard** [comment]
D'après équipe NEO : perte du token d'authentification au bout de 5h d'inactivité sur un NEO. Ce qui bloque l'accès aux applis sur internet (hors intranet).
L'utilisateur doit se réauthentifier sur une appli interne (au choix) qui permet de regénérer le token.
