### ISSUE TITLE
Modifier l ecran de consigne de prise de photo

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#396]
Pour les armes d'épaules présentant une crosse rétractable, la crosse doit être rétractée dans sa position permettant d'obtenir la longueur totale de l'arme la plus faible.

# Tasks

- [x] Ajouter le texte suivant à l'écran de consigne de prise de photo (le plus récent avec la carte) : 
" - En présence d'une crosse rétractable ou pliable sur l'arme : mettre la crosse dans sa configuration la plus **courte**."

**Comment by nutfdt** [comment]
<img width="187" alt="texte" src="https://github.com/datalab-mi/Basegun/assets/49862152/a8bfa8e9-1aca-40f7-b525-670bd0b46903">

**Comment by ClemGerard** [comment]
Ajout d'une modification sur le texte suite à retour d'Antoine Museau.
Navré pour la late notice
