### ISSUE TITLE
Simplifier les instructions sur la modale d'information

### ISSUE THREAD

**Issue by Carolinedanslesnuages** [datalab-mi/Basegun#81]
ETU lorsque je souhaite une information simplifier concernant la prise de photo

**Comment by leihuayi** [comment]
Dans https://github.com/datalab-mi/Basegun/blob/main/frontend/src/components/InstructionsModal.vue

**Comment by leihuayi** [comment]
- Replacer l'aspect modale par un aspect page
- Remplacer le bouton "fermer" de la modale par "prendre la photo (+icône photo)"
- Replacer les bullets du texte par 1. 2. 3.
- Rajouter une image "exemple de mauvaise photo" avant le bon exemple
- Rajouter des guides sur la photo du bon exemple (flèche canon vers droite, pointillées cadre, ...)
- Enlever la mention "si possible" dans le texte
- Enlever la grosse flèche avant "Pour un résultat optimal"

**Comment by Carolinedanslesnuages** [comment]
Oops, j'ai une petite question concernant la page : La page est à integrer dans le slide que l'on fait défilé au début ou bien après avoir cliqué sur démarrer ?
