### ISSUE TITLE
Portage Kubernetes

### ISSUE THREAD

**Issue by djadeau** [datalab-mi/Basegun#93]
- Création des manifestes YAML
- Création d'un environnement kubernetes
- Création d'un sous domaine basegin.fr

**Comment by leihuayi** [comment]
Est-ce que cette tâche est différente de https://github.com/datalab-mi/Basegun/pull/94 ? Si c'est la même chose on peut peut-être clore cette issue ?

**Comment by djadeau** [comment]
Sauf erreur de ma part, l'issue 93 est liée à la PR94. Cette issue sera cloturée automatiquement lorsque la PR sera validée.
